### ISSUE TITLE
`import: delegate library support not built-in`  error 

### ISSUE THREAD

**Issue by srustamo** [kspeeckaert/pyPdfCompare#1]
I'm on Mac 10.13.6

Error:

```
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1297.
from: can't read /var/mail/wand.image
from: can't read /var/mail/PIL
from: can't read /var/mail/io
: command not foundline 8:
: command not foundline 9:
./pyPdfCompare.py: line 10: syntax error near unexpected token `('
'/pyPdfCompare.py: line 10: `log = logging.getLogger(__name__)
```

**Comment by yarub123** [comment]
@srustamo did you ever fix this? this is so annoying

**Comment by srustamo** [comment]
No.

**Comment by yarub123** [comment]
@srustamo I think I figured it out, it's stupid. Try entering the python environment before trying to import whatever it is you tried to import. I think I figured it out 2 days ago, though right now don't remember exactly. Lemme know if that helps. If not, I can try looking through my log for the solution.

**Comment by yarub123** [comment]
@srustamo I take it that helped?

**Comment by srustamo** [comment]
I haven't used this package for a very long time and I would need some free time to setup the environment to check your solution. 

I figured your solution seems straight forward enough to close the issue.

Feel free to re-open it or create another issue if needed.

**Comment by yarub123** [comment]
Forsure. thanks for following up. Take care.
